### ISSUE TITLE
CSS size efficiency

### ISSUE THREAD

**Issue by techopswhiz** [mattpfeffer/tailwind-fontawesome#1]
Does this support automatically only including the css of the fontawesome icons you use in your project?

**Comment by mattpfeffer** [comment]
That's correct, it's using the Tailwind API to extend as intended. So if you're using Tailwind 3, the JIT compiler will only include the utility classes you actually use.

In Tailwind 2, if your not using JIT, it will bundle everything in development but still purge the unused classes in production builds.

**Comment by techopswhiz** [comment]
So you don't need to include fontawesome css separately?

**Comment by mattpfeffer** [comment]
Sorry, I think I misunderstood your original question.

Yes you do need to include Font Awesome separately. The recommended method to do this is via an official Font Awesome kit. The benefit of this is that you get to take advantage of the Font Awesome CDN, plus if you have 'Pro', Font Awesome will automatically take care of subsetting so you only load the css and web font glyphs you actually use. 

The downside of the above method is that it does load a some of the built-in Font Awesome classes which are a little redundant. Technically speaking, this plugin only needs the web fonts because we're referencing everything via unicode. So in theory you could just self-host the web fonts and declare them with @font-face. This would avoid extra CSS and JS, but keep in mind you wouldn't get the subsetting features from the CDN so you would end up loading the whole web font.

It really depends on your project as to which approach will be most efficient. I hope that helps.
